name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - run: |
          mkdir target_releases/
          touch target_releases/{foo,bar,baz}
      - uses: actions/upload-artifact@v3
        with:
          name: cross-build
          path: target_releases/*
  test:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: cross-build
      - run: |
          pwd
          ls -la
